image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: production
  USER_GITLAB: root
  APP_NAME: invoice
  REPO: logic1/invoice

stages:
  - build
  - package

maven-build:
  image: maven:3.6.0-jdk-8-alpine
  stage: build
  cache:
    paths:
      - .m2/
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2"
  script:
  - mvn --version
  - mvn package -B
  - echo this build is run --------------------
  - ls -alsh
  - ls -alsh target/
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: package
  script:
  - pwd
  - ls -alsh
  - whoami
  - uname -a
  - docker build -t registry.becopay.com/logic1/invoice .
  - docker login -u root -p $CI_BUILD_TOKEN registry.becopay.com
  - docker push registry.becopay.com/logic1/invoice
#  environment: production
#  when: manual