image: docker:latest
services:
  - name: postgres:11-alpine
    alias: postgres



variables:
#  DOCKER_DRIVER: overlay2
  SPRING_PROFILES_ACTIVE: production
  USER_GITLAB: root
  APP_NAME: invoice
  REPO: logic1/invoice
  DB_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_SCHEMA: invoicing
  POSTGRES_USER: jeus
  POSTGRES_PASSWORD: A123456b



stages:
  - build
  - package


maven-build:
  image: maven:3.6.0-jdk-8-alpine
  stage: build
  cache:
    paths:
      - .m2/
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2"
  script:
  - export SPRING_DATASOURCE_USERNAME=$POSTGRES_USER
  - export SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD
  - export SPRING_DATASOURCE_URL="jdbc:postgresql://${DB_HOST}:${POSTGRES_PORT}/${POSTGRES_USER}"
  - export SPRING_DATASOURCE_INITIALIZATION_MODE="always"
  - mvn --version
  - mvn package -B
  - echo this build is run --------------------
  - ls
  - ls -alsh target/*.jar
  artifacts:
    paths:
      - target/*.jar


docker-build:
  stage: package
  script:
  - pwd
  - ls -alsh
  - whoami
  - uname -a
  - echo $CI_DEPLOY_TOKEN_P
  - echo $CI_DEPLOY_TOKEN_U
  - echo $CI_BUILD_TOKEN
  - docker login -u $CI_DEPLOY_TOKEN_U -p $CI_DEPLOY_TOKEN_P registry.becopay.com/devops/java-docker
  - docker build -t registry.becopay.com/logic1/invoice .
  - docker login -u root -p $CI_BUILD_TOKEN registry.becopay.com
  - docker push registry.becopay.com/logic1/invoice
  only:
  - /^feature.*$/
# environment: feature*
#  when: manual