image: docker:latest
services:
  - name: docker:dind
    alias: dockerdind
  - name: postgres:11-alpine
    alias: postgres



variables:
#  DOCKER_DRIVER: overlay2
  SPRING_PROFILES_ACTIVE: production
  USER_GITLAB: root
  APP_NAME: invoice
  REPO: logic1/invoice
  DB_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_SCHEMA: invoicing
  POSTGRES_USER: jeus
  POSTGRES_PASSWORD: A123456b

stages:
#  - build
#  - test
  - develop
  - release
  - production

#build:
#  image: registry.becopay.com/devops/mvn-docker:latest
#  stage: build
#  tags:
#  - ir
#  cache:
#    paths:
#      - .m2/
#  variables:
#    MAVEN_OPTS: "-Dmaven.repo.local=.m2"
#  script:
#  - pwd
#  - ls -alsh
#  - ls -alsh /root
#  - export SPRING_DATASOURCE_USERNAME=$POSTGRES_USER
#  - export SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD
#  - export SPRING_DATASOURCE_URL="jdbc:postgresql://${DB_HOST}:${POSTGRES_PORT}/${POSTGRES_USER}"
#  - export SPRING_DATASOURCE_INITIALIZATION_MODE="always"
#  - ping -c 1 postgres
#  - mvn --version
#  - mvn package -B
#  - ls -alsh
#  - ls -alsh /root
#  - ls -alsh /
#  - ls -alsh target/*.jar
#  artifacts:
#    paths:
#      - target/*.jar
#  except:
#  - /^feature.*$/

#test:
#  stage: test
#  cache:
#    paths:
#      - target/
#  variables:
#    MAVEN_OPTS: "-Dmaven.repo.local=.m2"
#  script:
#  - echo "TEST PASS"
#
#test2:
#  stage: test
#  cache:
#    paths:
#      - target/
#  variables:
#    MAVEN_OPTS: "-Dmaven.repo.local=.m2"
#  script:
#  - echo "TEST 2 PASS CI TEST 2"


develop develop:
  stage: develop
  script:
  - uname -a
  - apk update
  - apk add openssh
#  - docker login -u $CI_DEPLOY_TOKEN_U -p $CI_DEPLOY_TOKEN_P registry.becopay.com/devops/java-docker
#  - docker build -t registry.becopay.com/logic1/invoice/develop:latest .
#  - docker login -u root -p $CI_BUILD_TOKEN registry.becopay.com
#  - docker push registry.becopay.com/logic1/invoice/develop:latest
#  - pwd
  - ls -alsh
  - ls -alsh /root
  - mkdir /root/.ssh
  - echo $ID_RSA > /root/.ssh/id_rsa
  - cp id_rsa.pub  /root/.ssh
  - chmod 600 /root/.ssh/id_rsa
  - chmod 600 /root/.ssh/id_rsa.pub
  - chmod 644 /root/.ssh
  - ls -alsh /root
  - cd
  - pwd
  - ls -alsh
  - ls -alsh /root/.ssh
  - cat /root/.ssh/id_rsa
  - cat /root/.ssh/id_rsa.pub
  - echo $DEVELOP_HOST
  - ssh -oStrictHostKeyChecking=no root@$DEVELOP_HOST 'uname -a'
  only:
  - develop

release:
  stage: release
  script:
  - docker login -u $CI_DEPLOY_TOKEN_U -p $CI_DEPLOY_TOKEN_P registry.becopay.com/devops/java-docker
  - docker build -t registry.becopay.com/logic1/invoice/release:latest .
  - docker login -u root -p $CI_BUILD_TOKEN registry.becopay.com
  - docker push registry.becopay.com/logic1/invoice
  only:
  - /^release.*$/

sandbox:
  stage: production
  script:
  - docker login -u $CI_DEPLOY_TOKEN_U -p $CI_DEPLOY_TOKEN_P registry.becopay.com/devops/java-docker
  - docker build -t registry.becopay.com/logic1/invoice/sandbox:latest .
  - docker login -u root -p $CI_BUILD_TOKEN registry.becopay.com
  - docker push registry.becopay.com/logic1/invoice
  only:
  - /^master.*$/

production:
  stage: production
  script:
  - docker login -u $CI_DEPLOY_TOKEN_U -p $CI_DEPLOY_TOKEN_P registry.becopay.com/devops/java-docker
  - docker build -t registry.becopay.com/logic1/invoice/production:latest .
  - docker login -u root -p $CI_BUILD_TOKEN registry.becopay.com
  - docker push registry.becopay.com/logic1/invoice
  only:
  - /^master.*$/
  when: manual