image: docker:latest
services:
  - name: docker:dind
    alias: dockerdind
  - name: postgres:11-alpine
    alias: postgres



variables:
#  DOCKER_DRIVER: overlay2
  SPRING_PROFILES_ACTIVE: production
  USER_GITLAB: root
  APP_NAME: invoice
  REPO: logic1/invoice
  DB_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_SCHEMA: invoicing
  POSTGRES_USER: jeus
  POSTGRES_PASSWORD: A123456b

stages:
#  - build
#  - test
  - develop
  - release
  - production

#build:
#  image: registry.becopay.com/devops/mvn-docker:latest
#  stage: build
#  tags:
#  - ir
#  cache:
#    paths:
#      - .m2/
#  variables:
#    MAVEN_OPTS: "-Dmaven.repo.local=.m2"
#  script:
#  - pwd
#  - ls -alsh
#  - ls -alsh /root
#  - export SPRING_DATASOURCE_USERNAME=$POSTGRES_USER
#  - export SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD
#  - export SPRING_DATASOURCE_URL="jdbc:postgresql://${DB_HOST}:${POSTGRES_PORT}/${POSTGRES_USER}"
#  - export SPRING_DATASOURCE_INITIALIZATION_MODE="always"
#  - ping -c 1 postgres
#  - mvn --version
#  - mvn package -B
#  - ls -alsh
#  - ls -alsh /root
#  - ls -alsh /
#  - ls -alsh target/*.jar
#  artifacts:
#    paths:
#      - target/*.jar
#  except:
#  - /^feature.*$/

#test:
#  stage: test
#  cache:
#    paths:
#      - target/
#  variables:
#    MAVEN_OPTS: "-Dmaven.repo.local=.m2"
#  script:
#  - echo "TEST PASS"
#
#test2:
#  stage: test
#  cache:
#    paths:
#      - target/
#  variables:
#    MAVEN_OPTS: "-Dmaven.repo.local=.m2"
#  script:
#  - echo "TEST 2 PASS CI TEST 2"


develop develop:
  stage: develop
  script:
  - uname -a
  - apk update
  - apk add openssh

#  - docker login -u $CI_DEPLOY_TOKEN_U -p $CI_DEPLOY_TOKEN_P registry.becopay.com/devops/java-docker
#  - docker build -t registry.becopay.com/logic1/invoice/develop:latest .
#  - docker login -u root -p $CI_BUILD_TOKEN registry.becopay.com
#  - docker push registry.becopay.com/logic1/invoice/develop:latest
#  - pwd
  - ls -alsh
  - ls -alsh /root
  - mkdir /root/.ssh
  - echo $ID_RSA > /root/.ssh/id_rsa
  - echo $ID_RSA_PUB > /root/.ssh/id_rsa.pub
  - chmod 644 /root/.ssh/id_rsa
  - chmod 744 /root/.ssh/id_rsa.pub
  - chmod 644 /root/.ssh
  - ls -alsh /root
  - cd
  - pwd
  - ls -alsh
  - ls -alsh /root/.ssh
  - cat /root/.ssh/id_rsa
  - cat /root/.ssh/id_rsa.pub
  - echo $DEVELOP_HOST
  - ssh -oStrictHostKeyChecking=no root@$DEVELOP_HOST 'uname -a'
  only:
  - develop

release:
  stage: release
  script:
  - docker login -u $CI_DEPLOY_TOKEN_U -p $CI_DEPLOY_TOKEN_P registry.becopay.com/devops/java-docker
  - docker build -t registry.becopay.com/logic1/invoice/release:latest .
  - docker login -u root -p $CI_BUILD_TOKEN registry.becopay.com
  - docker push registry.becopay.com/logic1/invoice
  only:
  - /^release.*$/

sandbox:
  stage: production
  script:
  - docker login -u $CI_DEPLOY_TOKEN_U -p $CI_DEPLOY_TOKEN_P registry.becopay.com/devops/java-docker
  - docker build -t registry.becopay.com/logic1/invoice/sandbox:latest .
  - docker login -u root -p $CI_BUILD_TOKEN registry.becopay.com
  - docker push registry.becopay.com/logic1/invoice
  only:
  - /^master.*$/

production:
  stage: production
  script:
  - docker login -u $CI_DEPLOY_TOKEN_U -p $CI_DEPLOY_TOKEN_P registry.becopay.com/devops/java-docker
  - docker build -t registry.becopay.com/logic1/invoice/production:latest .
  - docker login -u root -p $CI_BUILD_TOKEN registry.becopay.com
  - docker push registry.becopay.com/logic1/invoice
  only:
  - /^master.*$/
  when: manual




  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcnNhAAAAAwEAAQAAAgEAzCWrrPS+bAiAXKB/AYQKCOini7GhGwsRe7QmcG4SsJ9BUxrbQxQRztkeHnWGK46ltWaUtoG8nme1FKcQFX3CcNX9yENQTwnIkzRT0efsq1WS6jSvAB/60QNTaKJu5dUq713H9q/yMUxKg7X3uR2stWD2zlLorum+3zKjSCC13yKwR5x8haNVEq1O/i7j4SU8mKBddRPNAXFxGLTo4nlV65K/GgiitVSzrepG2WlrmEYOSOogqot/YPhmIvknHZkLCnxKVFmNGH0G92L6HAx3s899QzKn5jJcq64kdDDN4FUXNvC78OhEA/A6bJhtCsiimF5edg1MImDvb/PmdhW5tZVfyrc5aV3LhF6F/9qvDWUu/IP1ckax79ihGvPl05QPAnsNXa7ynLOj46/DKMJEF2W1zOzvMuVOKf5G2Qud2/78KpVTfLK7w9BMNI9CZ5Mp4WRpVOUvKdHg3qdNP3dq5qSXX3YvIG1sAkUpWn+7UP5TFWzxZR8ewXJfz5Ci7Kj8Bg0uKETSQCkaBB6n6qTFjC3HsdbLbv2/MrxKEY2ZAoS2Nfz/H/wkfClcnp8fMiMiVpnTU1502QfAIzGX5NRpr9Cwgu7gbjo4+iUg1pDQV+r8idZsakjeTQqNcgwVLRsPYUVXB9Ua3P0aSI8PnqzAEJ0Z+ld2F82RfgedOxYrVRUAAAdQwDD3LcAw9y0AAAAHc3NoLXJzYQAAAgEAzCWrrPS+bAiAXKB/AYQKCOini7GhGwsRe7QmcG4SsJ9BUxrbQxQRztkeHnWGK46ltWaUtoG8nme1FKcQFX3CcNX9yENQTwnIkzRT0efsq1WS6jSvAB/60QNTaKJu5dUq713H9q/yMUxKg7X3uR2stWD2zlLorum+3zKjSCC13yKwR5x8haNVEq1O/i7j4SU8mKBddRPNAXFxGLTo4nlV65K/GgiitVSzrepG2WlrmEYOSOogqot/YPhmIvknHZkLCnxKVFmNGH0G92L6HAx3s899QzKn5jJcq64kdDDN4FUXNvC78OhEA/A6bJhtCsiimF5edg1MImDvb/PmdhW5tZVfyrc5aV3LhF6F/9qvDWUu/IP1ckax79ihGvPl05QPAnsNXa7ynLOj46/DKMJEF2W1zOzvMuVOKf5G2Qud2/78KpVTfLK7w9BMNI9CZ5Mp4WRpVOUvKdHg3qdNP3dq5qSXX3YvIG1sAkUpWn+7UP5TFWzxZR8ewXJfz5Ci7Kj8Bg0uKETSQCkaBB6n6qTFjC3HsdbLbv2/MrxKEY2ZAoS2Nfz/H/wkfClcnp8fMiMiVpnTU1502QfAIzGX5NRpr9Cwgu7gbjo4+iUg1pDQV+r8idZsakjeTQqNcgwVLRsPYUVXB9Ua3P0aSI8PnqzAEJ0Z+ld2F82RfgedOxYrVRUAAAADAQABAAACADyy3q6YPp4kkPX5ionK1qj7dAWnFP3TdqlPUTaQo+H8GBI7pAH3z6uvBrOLwg7lZQPgskrpnEmFEGRJoBCjydJ+7exDh3dYs1iBcIKy8L2ovfwBGh9xYsQOtxgfY9XWYeO2AKSqf9qEkotC6ZsS5a0wXXHPWPvY6DW4+q+RekIUMFG6h5O8kqjw+tG842ioB7JhzCfpcUUCk9wCvlPIO/HFOijldGtx+dK2G8a8/47RFaI8auYKgB82/Ddd2XGFdbDyb69QyREE67NWrIL2egjuopH+V8msI72wE4qwkCYpZrOhNGBWzxJUtSpgz9sq+J1RQcjb/00hgU/KNzXZE9QPLanTmMbIcHClb8u4sGs4WiOUpkSMjNBGMngmtH74EZHc/7qs+MAPFO/rV+R0wRYNoguMTaVoPTza/CQ/tQ954XhbyEFRoY5Rm3akP4ynHymtg2z0eaqcp5IT2Vr/5pPqx9bKmvGW/8Zzwva47LREW4uB4hDuWGRmXyakgtIEVBNtMuUVoh7T/MBDRzUHwajrWsiXNfaN/xbMTtXffYDhzzeN6tk4bvcf2/lQ7o0zymC9KRcRNQ/h5CaGDkdm5lU99FxlgzbjHIPDhti+1kBmXsbbJ9pGYwidsU8Y24qVe8Grlp3XNPMxNNiMZna8ob8iWyWEry+8DcgO0k+pH9ZpAAABAQDsWyI+abhGi+4Y/DGtGu16/XHgEZif2kPDadaqHUZ7rYNyjoXOAa6Xk8IpU78iBjyFyFVujYluznSkfo/7lif7f349sXFTgaoF8Atk1Xk35qLQfIzDZdcWgiNjTNYiszHEJm8qbi/XwBWoPehBVUsFeptH2yI+PXk9gqqMWhKfNdUQtklP+m4kgPXXIQb3/WMhVnPlCpKNbJ3tM7Pz0pk7yZaLgTHrr4DOZQ53//d1xlI4XMgHOfNk3N2PHdQJPUeR49cG013JDy7bmxc/Gm032pmzVF/G10OWuUioOXjrK54irVWE14eRe3aTG5yjTUP4FCE8kg7mF9GoSOolMGL2AAABAQD8gmyFyjRGIKqBgBJ48bEXOv2UYsewDDE5rQEzSlpO4qMGsFaN24RaevNthXSle/5Cgowk6z8pEdp5VGWQXwNhlGb+zMQlI5O3/FoQRvcLfnjew5lxi+da0HqO5W+0lOLYzpYzW1FXD5VLkiy1TyyeN2LT6ZWHf9iiP9nRc9yUql6mbxa1z1g+ohPEt5abH3eoLcoBdlqF8yvKz7Bg0pS+1IScp5yZNx3o+x8kISTiQCdgUAuqXLyTc55Z9xGb0DNmHFAiqZXmubHQzjKllCaRdpiG+ZY9mmVxMSfftuI8oHG8eiXMeqQwo0+OGucw8pz8E2ZnTmHH5siBLw4K/CqjAAABAQDO+BpcLSV4DihFOZ8uIhnlkeKFm1JK9O1uH9FtaUrO3/3VnRChtxkWEOjl4sszLJcrqNh9e6qB8tSgfypOiLd4KSxUwE1FzIdkdeWWhbbpoE9DPDsZKe6x/z/5de+/c7iu9qseEl4oLxuouRFPTdS/VQ7vxVLiaLhTN9Sya83nM/4KW7fSVsv73kccpUF5hRHNXOUnQFoSWlLVjV/N5z3h1lL0UaOOiq8drtz7dDW9OUD3bshKcIoWp0Ss5OKaWNjSm6E1RJTtAVVp9zLjBi5LKVUaz1MiZYYbto+rUnMb8HUnKubYKfOdJHi2Iw0nIyNvfjy017KC3/e0YYf9ZXTnAAAAFGFsa2hhbmRhbmlAZ21haWwuY29tAQIDBAUG
  -----END OPENSSH PRIVATE KEY-----